sonar.projectKey = hms-frontend
sonar.projectName = hms-frontend
Node App sonar.projectVersion = 1.0
sonar.sources = src
sonar.language = js
sonar.sourceEncoding = UTF-8
# Exclusions
sonar.exclusions = node_modules/**,test/**,.angular/**
# Test coverage
sonar.coverage.exclusions = **
# sonar.tests=test sonar.javascript.lcov.reportPaths=coverage/lcov.info
# Server & auth
sonar.host.url = http://localhost:9000
sonar.login =  sqp_474bebb448f8b1dd93d236a5c80e6a15556c2ce9





