name: Deploy HMS FRONTEND

on:
  push:
    branches:
      - feature/sprint_5/merin

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy EC2 FRONTEND
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_MERIN_HOST }}
          username: ${{ secrets.EC2_MERIN_USER }}
          key: ${{ secrets.EC2_MERIN_SSH_KEY }}
          script: |
            cd hms-frontend-pod3
            git pull origin feature/sprint_5/merin
            npm ci
            npm run build -- --configuration production
            sudo rm -rf /var/www/html/*
            sudo cp -r dist/hms-frontend/browser/* /var/www/html/
            sudo systemctl restart nginx